<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\common.props"/>

    <ItemGroup>
        <!-- Quartz -->
        <PackageReference Include="Quartz"/>
        <PackageReference Include="Quartz.Jobs"/>
        <PackageReference Include="Quartz.Plugins"/>
        <PackageReference Include="Quartz.Serialization.Json"/>

        <!-- Castle Windsor / Common Logging -->
        <PackageReference Include="Castle.Windsor"/>
        <PackageReference Include="Castle.Core"/>
        <PackageReference Include="Common.Logging"/>

        <!-- PPWCode -->
        <PackageReference Include="PPWCode.Vernacular.Exceptions.III"/>

        <!-- System -->
        <PackageReference Include="System.Data.SqlClient"/>
        <PackageReference Include="System.Configuration.ConfigurationManager"/>
    </ItemGroup>

</Project>
