<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- target frameworks -->
    <TargetFrameworks>netstandard2.0;net48;net481;net6.0;net8.0</TargetFrameworks>

    <!-- nuget package -->
    <IsPackable>true</IsPackable>

    <!-- Stylecop -->
    <CodeAnalysisRuleSet>..\StyleCop.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <!-- Quartz -->
    <PackageReference Include="Quartz" Version="3.5.*" />
    <PackageReference Include="Quartz.Jobs" Version="3.5.*" />
    <PackageReference Include="Quartz.Plugins" Version="3.5.*" />
    <PackageReference Include="Quartz.Serialization.Json" Version="3.5.*" />

    <!-- Castle Windsor / Common Logging -->
    <PackageReference Include="Castle.Windsor" Version="5.1.1" />
    <PackageReference Include="Castle.Core" Version="4.4.1" />
    <PackageReference Include="Common.Logging" Version="3.4.1" />

    <!-- PPWCode -->
    <PackageReference Include="PPWCode.Vernacular.Exceptions.III" Version="1.0.0" />
    
    <!-- System -->
    <PackageReference Include="System.Data.SqlClient" Version="*" />
  </ItemGroup>

  <Choose>
    <When Condition=" '$(TargetFramework)' == 'net6.0'">
      <ItemGroup>
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.*" />
      </ItemGroup>
    </When>
    <When Condition=" '$(TargetFramework)' == 'net8.0'">
      <ItemGroup>
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.*" />
      </ItemGroup>
    </When>
    <When Condition=" '$(TargetFramework)' == 'netstandard20' Or '$(TargetFramework)' == 'net48' Or '$(TargetFramework)' == 'net481'">
      <ItemGroup>
        <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.*" />
      </ItemGroup>
    </When>
  </Choose>

</Project>
